export const REQUESTED_PROFILE = 'REQUESTED_PROFILE'
export const REQUESTED_PROFILE_SUCCESS = 'REQUESTED_PROFILE_SUCCESS'
export const REQUESTED_PROFILE_ERROR = 'REQUESTED_PROFILE_ERROR'

export const REQUESTED_NEW_STREAM = 'REQUESTED_NEW_STREAM'
export const REQUESTED_NEW_STREAM_SUCCESS = 'REQUESTED_NEW_STREAM_SUCCESS'
export const REQUESTED_NEW_STREAM_ERROR = 'REQUESTED_NEW_STREAM_ERROR'

export const REQUESTED_STREAMS = 'REQUESTED_STREAMS'
export const REQUESTED_STREAMS_SUCCESS = 'REQUESTED_STREAMS_SUCCESS'
export const REQUESTED_STREAMS_ERROR = 'REQUESTED_STREAMS_ERROR'

export const CHANGED_INPUT = 'CHANGED_INPUT'
