export const REQUESTED_NEW_THREAD = 'REQUESTED_NEW_THREAD'
export const REQUESTED_NEW_THREAD_SUCCESS = 'REQUESTED_NEW_THREAD_SUCCESS'
export const REQUESTED_NEW_THREAD_ERROR = 'REQUESTED_NEW_THREAD_ERROR'

export const REQUESTED_PROFILE = 'REQUESTED_PROFILE'
export const REQUESTED_PROFILE_SUCCESS = 'REQUESTED_PROFILE_SUCCESS'
export const REQUESTED_PROFILE_ERROR = 'REQUESTED_PROFILE_ERROR'

export const REQUESTED_THREADS = 'REQUESTED_THREADS'
export const REQUESTED_THREADS_SUCCESS = 'REQUESTED_THREADS_SUCCESS'
export const REQUESTED_THREADS_ERROR = 'REQUESTED_THREADS_ERROR'

export const REQUESTED_NEW_STREAM = 'REQUESTED_NEW_STREAM'
export const REQUESTED_NEW_STREAM_SUCCESS = 'REQUESTED_NEW_STREAM_SUCCESS'
export const REQUESTED_NEW_STREAM_ERROR = 'REQUESTED_NEW_STREAM_ERROR'

export const CHANGED_INPUT = 'CHANGED_INPUT'
