export const REQUESTED_NEW_THREAD = "REQUESTED_NEW_THREAD";
export const REQUESTED_NEW_THREAD_SUCCESS = "REQUESTED_NEW_THREAD_SUCCESS";
export const REQUESTED_NEW_THREAD_ERROR = "REQUESTED_NEW_THREAD_ERROR";

export const REQUESTED_PROFILE = "REQUESTED_PROFILE";
export const REQUESTED_PROFILE_SUCCESS = "REQUESTED_PROFILE_SUCCESS";
export const REQUESTED_PROFILE_ERROR = "REQUESTED_PROFILE_ERROR";
